// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4vd-0RHybruTTuU3tLWqcyFk3UkUblw',
    appId: '1:510308197174:web:90bae94dcd9d8dc7764997',
    messagingSenderId: '510308197174',
    projectId: 'chat-app-with-backend',
    authDomain: 'chat-app-with-backend.firebaseapp.com',
    storageBucket: 'chat-app-with-backend.appspot.com',
    measurementId: 'G-MD74VFEW7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7aVG6kKAkWlk_WMwAOHEZnq3Fkof3bGc',
    appId: '1:510308197174:android:5041fbc47f08ad7a764997',
    messagingSenderId: '510308197174',
    projectId: 'chat-app-with-backend',
    storageBucket: 'chat-app-with-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUiFAPz9w333oSj4XqwswqyEBsm6J3ge0',
    appId: '1:510308197174:ios:5b31914063826261764997',
    messagingSenderId: '510308197174',
    projectId: 'chat-app-with-backend',
    storageBucket: 'chat-app-with-backend.appspot.com',
    iosClientId: '510308197174-sbhasjo95outnm8nrdjp1q4vjsb1qco5.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
